initial workflow file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,9 +1,7 @@
 name: ci
 on: [push]
 jobs:
-  # check if the tests pass TypeScript check step
-  # and there are no exclusive tests accidentally left in the code
-  checks:
+  e2e:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout 🛎️
@@ -12,18 +10,25 @@ jobs:
       - name: Install 📦
         uses: cypress-io/github-action@v6
         with:
-          runTests: false
-      - name: Check types 🧹
-        run: npm run lint
-      - name: Catch it.only tests 🫴
-        run: npm run only
+          start: npm start
+          wait-on: 'http://127.0.0.1:3000'
 
-  # run end-to-end and component tests in parallel
-  # https://github.com/bahmutov/cypress-workflows
-  tests:
-    needs: checks
-    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
-    with:
-      nE2E: 4 # use N containers for E2E tests
-      start: npm start
-      wait-on: 'http://127.0.0.1:3000'
+      # generate image diffs between two gold images
+      # and the two screenshots
+      # Tip: always run this step, even if the tests fail
+      # Tip 2: use "|| true" to ignore any diff errors
+      # since there might be no screenshots
+      - name: Generate image diffs 📸
+        run: |
+          # npx odiff ...
+
+      # after the test run completes store the screenshots and diffs
+      - name: Save screenshots 📸
+        # https://github.com/actions/upload-artifact
+        uses: actions/upload-artifact@v4
+        # always upload the screenshots, even if the tests fail
+        if: always()
+        # with:
+        # name: <artifact name>
+        # path: <folder with screenshots>
+        # if-no-files-found: ignore
